extend = "../Makefile.toml"

[tasks.uf2]
command = "elf2uf2-rs"
args = ["../target/thumbv6m-none-eabi/release/c1minimal", "../target/thumbv6m-none-eabi/release/c1minimal.uf2"]
dependencies = ["build-release"]
install_crate = "elf2uf2-rs"

[tasks.bin]
command = "llvm-objcopy"
args = ["-Obinary", "../target/thumbv6m-none-eabi/release/c1minimal", "../target/thumbv6m-none-eabi/release/c1minimal.bin"]
dependencies = ["build-release"]
